import { Course } from '@/types'

export const DEFAULT_COURSES: Course[] = [
  {
    id: 'emerald-greens-gold',
    name: 'Emerald Greens Gold',
    location: 'Emerald Greens Golf Club',
    state: 'MN',
    holeCount: 18,
    par: 72,
    holes: [
      { holeNumber: 1, par: 5, handicap: 13, yardage: 520 },
      { holeNumber: 2, par: 4, handicap: 7, yardage: 385 },
      { holeNumber: 3, par: 4, handicap: 9, yardage: 410 },
      { holeNumber: 4, par: 3, handicap: 15, yardage: 165 },
      { holeNumber: 5, par: 5, handicap: 17, yardage: 545 },
      { holeNumber: 6, par: 4, handicap: 3, yardage: 430 },
      { holeNumber: 7, par: 3, handicap: 11, yardage: 185 },
      { holeNumber: 8, par: 4, handicap: 1, yardage: 455 },
      { holeNumber: 9, par: 4, handicap: 5, yardage: 420 },
      { holeNumber: 10, par: 4, handicap: 6, yardage: 395 },
      { holeNumber: 11, par: 5, handicap: 16, yardage: 550 },
      { holeNumber: 12, par: 3, handicap: 18, yardage: 155 },
      { holeNumber: 13, par: 5, handicap: 14, yardage: 530 },
      { holeNumber: 14, par: 3, handicap: 12, yardage: 175 },
      { holeNumber: 15, par: 3, handicap: 8, yardage: 160 },
      { holeNumber: 16, par: 5, handicap: 10, yardage: 560 },
      { holeNumber: 17, par: 4, handicap: 4, yardage: 440 },
      { holeNumber: 18, par: 4, handicap: 2, yardage: 465 },
    ],
  },
  {
    id: 'emerald-greens-silver',
    name: 'Emerald Greens Silver',
    location: 'Emerald Greens Golf Club',
    state: 'MN',
    holeCount: 18,
    par: 72,
    holes: [
      { holeNumber: 1, par: 4, handicap: 9, yardage: 380 },
      { holeNumber: 2, par: 3, handicap: 17, yardage: 157 },
      { holeNumber: 3, par: 4, handicap: 3, yardage: 422 },
      { holeNumber: 4, par: 4, handicap: 7, yardage: 373 },
      { holeNumber: 5, par: 4, handicap: 15, yardage: 347 },
      { holeNumber: 6, par: 3, handicap: 13, yardage: 168 },
      { holeNumber: 7, par: 5, handicap: 5, yardage: 576 },
      { holeNumber: 8, par: 5, handicap: 11, yardage: 503 },
      { holeNumber: 9, par: 4, handicap: 1, yardage: 404 },
      { holeNumber: 10, par: 4, handicap: 10, yardage: 358 },
      { holeNumber: 11, par: 4, handicap: 2, yardage: 437 },
      { holeNumber: 12, par: 4, handicap: 6, yardage: 404 },
      { holeNumber: 13, par: 3, handicap: 16, yardage: 185 },
      { holeNumber: 14, par: 5, handicap: 8, yardage: 530 },
      { holeNumber: 15, par: 3, handicap: 18, yardage: 120 },
      { holeNumber: 16, par: 4, handicap: 12, yardage: 368 },
      { holeNumber: 17, par: 4, handicap: 4, yardage: 435 },
      { holeNumber: 18, par: 5, handicap: 14, yardage: 532 },
    ],
  },
  {
    id: 'valleywood-golf',
    name: 'Valleywood Golf Course',
    location: 'Valleywood',
    state: 'MN',
    holeCount: 18,
    par: 72,
    holes: [
      { holeNumber: 1, par: 4, handicap: 4, yardage: 330 },
      { holeNumber: 2, par: 3, handicap: 14, yardage: 136 },
      { holeNumber: 3, par: 4, handicap: 8, yardage: 372 },
      { holeNumber: 4, par: 5, handicap: 18, yardage: 463 },
      { holeNumber: 5, par: 4, handicap: 16, yardage: 308 },
      { holeNumber: 6, par: 4, handicap: 10, yardage: 302 },
      { holeNumber: 7, par: 3, handicap: 12, yardage: 160 },
      { holeNumber: 8, par: 4, handicap: 6, yardage: 420 },
      { holeNumber: 9, par: 5, handicap: 2, yardage: 460 },
      { holeNumber: 10, par: 4, handicap: 7, yardage: 376 },
      { holeNumber: 11, par: 3, handicap: 17, yardage: 133 },
      { holeNumber: 12, par: 5, handicap: 15, yardage: 470 },
      { holeNumber: 13, par: 3, handicap: 13, yardage: 165 },
      { holeNumber: 14, par: 4, handicap: 11, yardage: 337 },
      { holeNumber: 15, par: 5, handicap: 9, yardage: 472 },
      { holeNumber: 16, par: 4, handicap: 1, yardage: 380 },
      { holeNumber: 17, par: 4, handicap: 3, yardage: 402 },
      { holeNumber: 18, par: 4, handicap: 5, yardage: 367 },
    ],
  },
  {
    id: 'lost-spur',
    name: 'Lost Spur Golf Course',
    location: 'Lost Spur',
    state: 'MN',
    holeCount: 9,
    par: 34,
    holes: [
      { holeNumber: 1, par: 4, handicap: 1, yardage: 346 },
      { holeNumber: 2, par: 4, handicap: 15, yardage: 253 },
      { holeNumber: 3, par: 3, handicap: 9, yardage: 157 },
      { holeNumber: 4, par: 4, handicap: 11, yardage: 290 },
      { holeNumber: 5, par: 4, handicap: 13, yardage: 302 },
      { holeNumber: 6, par: 3, handicap: 8, yardage: 212 },
      { holeNumber: 7, par: 5, handicap: 5, yardage: 425 },
      { holeNumber: 8, par: 3, handicap: 12, yardage: 145 },
      { holeNumber: 9, par: 4, handicap: 17, yardage: 230 },
    ],
  },
  {
    id: 'birnamwood',
    name: 'Birnamwood Golf Course',
    location: 'Burnsville',
    state: 'MN',
    holeCount: 9,
    par: 27,
    holes: [
      { holeNumber: 1, par: 3, handicap: 15, yardage: 122 },
      { holeNumber: 2, par: 3, handicap: 13, yardage: 123 },
      { holeNumber: 3, par: 3, handicap: 1, yardage: 171 },
      { holeNumber: 4, par: 3, handicap: 3, yardage: 139 },
      { holeNumber: 5, par: 3, handicap: 17, yardage: 109 },
      { holeNumber: 6, par: 3, handicap: 9, yardage: 139 },
      { holeNumber: 7, par: 3, handicap: 5, yardage: 165 },
      { holeNumber: 8, par: 3, handicap: 11, yardage: 142 },
      { holeNumber: 9, par: 3, handicap: 7, yardage: 157 },
    ],
  },
]

export function initializeCoursesIfNeeded() {
  if (typeof window === 'undefined') return

  const existingCourses = localStorage.getItem('golfCourses')
  if (!existingCourses) {
    localStorage.setItem('golfCourses', JSON.stringify(DEFAULT_COURSES))
  }
}
